version: '3.8'

services:
  nginx:
    image: nginx
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    networks:
      - Inception
    restart: unless-stopped
    depends_on:
      - wordpress
    volumes:
      - wordpress_volume:/var/www/html
  mariadb:
    image: mariadb
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb_volume:/var/lib/mysql
    env_file:
      - .env
    healthcheck:
      interval: 5s
      timeout: 30s
      retries: 10
      start_period: 5s  
      test: ["CMD", "mysqladmin", "ping", "--silent"] 
    restart: unless-stopped
    expose:
      - 3306
    networks:
      - Inception
  wordpress:
    image: wordpress
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wordpress_volume:/var/www/html
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - Inception
    expose:
      - 9000
volumes:
  mariadb_volume:
    driver: local # Specifies that the volume will be managed by the local driver
    driver_opts: # Indicates that the volume will not be managed by a specific volume driver type.
      type: none
      device: /home/mgranate/data/mariadb
      o: bind 
  wordpress_volume:
    driver: local
    driver_opts: 
      type: none
      device: /home/mgranate/data/wordpress
      o: bind
      # A bind mount allows the user to link a specific directory or file on the host machine to a directory inside the container
      # Any changes made to the files or directories within the bind-mounted path on the host are immediately reflected
      # inside the container and vice versa
      # This is particularly usefull for scenarios where the user wants to manage data outside of the container
      #and maintain it even when the container is not running.
networks:
  Inception:  
